### ISSUE TITLE
Possible to create malformed XML

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#21]
I had an object with a name that wasn't encoded properly in the XML for `DeleteObjects()`.

The name was one of:

- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%01
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%02
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%03
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%04
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%05
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%06
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%07
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%08
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%0B
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%0C
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%0D
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%0E
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%0F
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%10
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%11
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%12
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%13
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%14
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%15
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%16
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%17
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%18
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%19
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%1A
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%1B
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%1C
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%1D
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%1E
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%1F
- https://s3.eu-west-1.amazonaws.com/test-ordering/test/%C3%B7

**Comment by Genbox** [comment]
A lot of those values are not valid in XML 1.0 (and discouraged in XML 1.1). Amazon rejects them for that reason. I have changed the XML writer in SimpleS3 to throw an exception when it encounters one of these characters.

Since it is possible to PUT objects with 0x1 as the key, but not delete it using DeleteObjects(), I'm going to add a usability layer that by default will warn against having 0x1 in the object key. It should be so that all objects created using this library will be possible to download, copy and delete no matter what transport serialization method is used.

Closing this issue.
